langauge: c
cache: packages
sudo: required

addons:
  apt:
    packages:
      - r-base-dev

script:
  - R CMD build .

r_packages: 
  - devtools
  - dplyr
  - oro.dicom
  - oro.nifti
  - lambda.r
  - rapportools
  - papayar

r_github_packages: 
  - OHDSI/DatabaseConnector