langauge: generic
cache: packages
sudo: required

addons:
  apt:
    packages:
      - r-base-dev

script:
  - R CMD build .

r_packages:
  - devtools
  - dplyr
  - oro.dicom
  - oro.nifti
  - doSNOW
  - rapportools
  - foreach
  - R6
  - parallel
  - stringr

r_github_packages:
  - OHDSI/DatabaseConnector
  - OHDSI/SqlRender
