langauge: r
cache: packages
sudo: required

addons:
  apt:
    packages:
      - r-base-dev

r_packages:
  - devtools
  - dplyr
  - oro.dicom
  - oro.nifti
  - doSNOW
  - rapportools
  - foreach
  - R6
  - parallel
  - stringr

r_github_packages:
  - OHDSI/DatabaseConnector
  - OHDSI/SqlRender

notifications:
  email:
    on_success: change
    on_failure: change

before_script:
  - wget -P ~ $CT_SAMPLE
  - mkdir ~/signedrangeimages
  - tar -xvf ~/signedrangeimages.tar.bz2 -C ~/signedrangeimages

script:
  - R CMD build .
  - R CMD INSTALL *.tar.gz --library=$R_LIB_PATH

after_success:
  - Rscript tests/testRadETL.R
